name: Test Action

on:
  workflow_dispatch:
    inputs:
      name-to-greet:
        description: Name to Greet

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Action
        uses: ./
        with:
          name-to-greet: ${{ inputs.name-to-greet }}
          myNewInput: This is my input
          firstName: John
          lastName: Wick